/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Info about one webcam on the system. Returned by `listDevices()`. */
export interface DeviceInfo {
  index: number
  name: string
  /**
   * "V4L2" / "MSMF" / "AVFoundation" — useful for diagnostics
   * and for the `face-lock doctor` subcommand.
   */
  backend: string
}
/**
 * Enumerate video devices on the system. Returns one entry per physical
 * webcam, with the index that should be passed to `Camera.tryOpen()`
 * or `new Camera(index, ...)`. Returns 0..N.
 */
export declare function listDevices(): NapiResult
/**
 * JS-friendly "try" pattern: returns `Camera` on success, `null` on
 * failure. This is the path `src/camera.js` will use in v0.2.0 to
 * fall back to the ffmpeg pipeline when the native path is
 * unavailable (permission denied, driver not loaded, no devices, etc.).
 *
 * Internally calls the same `try_open_internal` as the constructor
 * and discards the error. Errors are not logged here on purpose —
 * the caller (src/camera.js) logs them with face-lock's own
 * diagnostic context.
 */
export declare function tryOpen(index: number, width: number, height: number): Camera | null
/**
 * A webcam handle. Constructed by `new Camera(index, width, height)`
 * (throws on failure) or `Camera.tryOpen(index, width, height)`
 * (returns `null` on failure). Released by `close()`. The handle is
 * `&mut` on every method because nokhwa's API is not thread-safe and
 * the napi-rs runtime may invoke methods from any thread.
 */
export declare class Camera {
  /**
   * Construct a `Camera` for the device at `index` (from
   * `listDevices()`) at the given resolution. Pass `index = -1` to
   * use the default (first) device.
   *
   * **Caveat:** napi-rs 2.x's `#[napi(constructor)]` does not
   * support `Result<Self>`. A failure here will **panic** the
   * native thread and abort the Node process — do not call this
   * without verifying the device is openable first. For
   * "best-effort" opening that returns `null` on failure, use
   * `Camera.tryOpen()` (the free function).
   *
   * The pattern face-lock uses in `src/camera.js` is:
   * ```js
   * const devs = listDevices();
   * if (devs.length === 0) return null;  // skip native path
   * return Camera.tryOpen(0, 320, 240);    // null on failure
   * ```
   * `new Camera(...)` is only used in tests and the `face-lock doctor`
   * subcommand, where the user has explicitly asked for native
   * capture and a hard failure is the right behavior.
   */
  constructor(index: number, width: number, height: number)
  /**
   * Capture one frame and return it as JPEG bytes. Single-frame
   * semantics: each call blocks until the camera delivers a frame.
   * On Linux V4L2 this is one `VIDIOC_DQBUF` cycle (~10-30ms on a
   * USB webcam).
   *
   * Returns a Node `Buffer` (Uint8Array) — JS can write it directly
   * to a file with `fs.writeFileSync`.
   */
  captureJpeg(): NapiResult
  /** Release the device handle. Idempotent. */
  close(): NapiResult
}
